website/auth.py
import re
from flask import Blueprint, flash, redirect, render_template, url_for, request, session
from flask_login import login_user, login_required, logout_user, current_user
from .models import User, Game, Leaderboard, PlayerScore, Event, db
from datetime import datetime

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    data = request.form
    dbUser = ""
    if request.method == 'POST':
        inputEmail = request.form.get('email')
        inputPassword = request.form.get('password1')
        dbUser = User.query.filter_by(email=inputEmail).first()
        if dbUser:
            if dbUser.check_password(inputPassword):
                flash('Logged in successfully', category='success')
                login_user(dbUser, remember=True)
                return redirect(url_for('views.home'))
        else:
            flash('Invalid email or password', category='error')
    return render_template('login.html', user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        regemail = request.form.get('email')
        regusername = request.form.get('username')
        regpassword1 = request.form.get('password1')
        regpassword2 = request.form.get('password2')
        is_game_owner = True if request.form.get('is_game_owner') else False

        if len(regemail) < 4:
            flash('Email must be greater than 4 characters.', category='error')
        elif len(regusername) < 2:
            flash('Username must be greater than 1 character.', category='error')
        elif regpassword1 != regpassword2:
            flash('Passwords must match', category='error')
        elif len(regpassword1) < 7:
            flash('Minimum 8 characters required', category='error')
        else:
            new_user = User(
                username=regusername,
                email=regemail,
                is_game_owner=is_game_owner
            )
            new_user.set_password(regpassword1)  # Set the password
            db.session.add(new_user)  # Add the user to the session
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('register.html', user=current_user)

@auth.route('/admin', methods=['GET', 'POST'])
def admin_login():
    if request.method == 'POST':
        password = request.form.get('password')
        if password == 'ADMINPASS':  # Replace with your desired admin password
            session['admin_logged_in'] = True
            return redirect(url_for('auth.admin_dashboard'))
        else:
            flash('Invalid password. Please try again.', 'error')
            return redirect(url_for('auth.admin_login'))
    return render_template('admin_login.html')

@auth.route('/admin/logout')
def admin_logout():
    session.pop('admin_logged_in', None)
    return redirect(url_for('auth.admin_login'))

@auth.route('/admin/dashboard')
def admin_dashboard():
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    users = User.query.all()
    games = Game.query.all()
    leaderboards = Leaderboard.query.all()
    player_scores = PlayerScore.query.all()
    events = Event.query.all()
    return render_template('admin_dashboard.html', users=users, games=games, leaderboards=leaderboards, player_scores=player_scores, events=events)

@auth.route('/add_user', methods=['POST'])
def add_user():
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    is_game_owner = True if request.form.get('is_game_owner') else False
    new_user = User(username=username, email=email, is_game_owner=is_game_owner)
    new_user.set_password(password)
    db.session.add(new_user)
    db.session.commit()
    return redirect(url_for('auth.admin_dashboard'))

@auth.route('/edit_user/<int:user_id>', methods=['GET', 'POST'])
def edit_user(user_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    user = User.query.get_or_404(user_id)
    if request.method == 'POST':
        user.username = request.form.get('username')
        user.email = request.form.get('email')
        user.is_game_owner = True if request.form.get('is_game_owner') else False
        db.session.commit()
        return redirect(url_for('auth.admin_dashboard'))
    return render_template('edit_user.html', user=user)

@auth.route('/delete_user/<int:user_id>')
def delete_user(user_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    user = User.query.get_or_404(user_id)

    # Delete associated data
    PlayerScore.query.filter_by(player_id=user.id).delete()
    Event.query.filter_by(owner_id=user.id).delete()
    Game.query.filter_by(owner_id=user.id).delete()

    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('auth.admin_dashboard'))

@auth.route('/add_game', methods=['POST'])
def add_game():
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    title = request.form.get('title')
    description = request.form.get('description')
    release_date = datetime.strptime(request.form.get('release_date'), '%Y-%m-%d')
    owner_id = request.form.get('owner_id')
    new_game = Game(title=title, description=description, release_date=release_date, owner_id=owner_id)
    db.session.add(new_game)
    db.session.commit()
    return redirect(url_for('auth.admin_dashboard'))

@auth.route('/edit_game/<int:game_id>', methods=['GET', 'POST'])
def edit_game(game_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    game = Game.query.get_or_404(game_id)
    users = User.query.all()
    if request.method == 'POST':
        game.title = request.form.get('title')
        game.description = request.form.get('description')
        game.release_date = datetime.strptime(request.form.get('release_date'), '%Y-%m-%d')
        game.owner_id = request.form.get('owner_id')
        db.session.commit()
        return redirect(url_for('auth.admin_dashboard'))
    return render_template('edit_game.html', game=game, users=users)

@auth.route('/delete_game/<int:game_id>')
def delete_game(game_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    game = Game.query.get_or_404(game_id)

    # Delete associated data
    Leaderboard.query.filter_by(game_id=game.id).delete()
    PlayerScore.query.filter_by(game_id=game.id).delete()
    Event.query.filter_by(game_id=game.id).delete()

    db.session.delete(game)
    db.session.commit()
    return redirect(url_for('auth.admin_dashboard'))

@auth.route('/transfer_ownership/<int:game_id>', methods=['GET', 'POST'])
def transfer_ownership(game_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    game = Game.query.get_or_404(game_id)
    game_owners = User.query.filter_by(is_game_owner=True).all()

    if request.method == 'POST':
        new_owner_id = request.form.get('new_owner_id')
        game.owner_id = new_owner_id
        db.session.commit()
        return redirect(url_for('auth.admin_dashboard'))

    return render_template('transfer_ownership.html', game=game, game_owners=game_owners)

@auth.route('/add_leaderboard', methods=['POST'])
def add_leaderboard():
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    game_id = request.form.get('game_id')
    name = request.form.get('name')

    # Check if the game already has a leaderboard
    existing_leaderboard = Leaderboard.query.filter_by(game_id=game_id).first()

    if existing_leaderboard:
        # If a leaderboard already exists, append a number to the name
        count = Leaderboard.query.filter_by(game_id=game_id).count()
        name = f"{name} {count + 1}"
    else:
        # If it's the first leaderboard for the game, set the name to "Main Leaderboard"
        name = "Main Leaderboard"

    new_leaderboard = Leaderboard(game_id=game_id, name=name)
    db.session.add(new_leaderboard)
    db.session.commit()
    return redirect(url_for('auth.admin_dashboard'))

@auth.route('/edit_leaderboard/<int:leaderboard_id>', methods=['GET', 'POST'])
def edit_leaderboard(leaderboard_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    leaderboard = Leaderboard.query.get_or_404(leaderboard_id)
    games = Game.query.all()
    if request.method == 'POST':
        leaderboard.game_id = request.form.get('game_id')
        db.session.commit()
        return redirect(url_for('auth.admin_dashboard'))
    return render_template('edit_leaderboard.html', leaderboard=leaderboard, games=games)

@auth.route('/delete_leaderboard/<int:leaderboard_id>')
def delete_leaderboard(leaderboard_id):
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    leaderboard = Leaderboard.query.get_or_404(leaderboard_id)

    # Delete associated player scores
    PlayerScore.query.filter_by(leaderboard_id=leaderboard.id).delete()

    db.session.delete(leaderboard)
    db.session.commit()
    return redirect(url_for('auth.admin_dashboard'))

@auth.route('/add_player_score', methods=['POST'])
def add_player_score():
    if not session.get('admin_logged_in'):
        return redirect(url_for('auth.admin_login'))
    player_id = request.form.get('player_id')
    leaderboard_id = request.form.get('leaderboard_id')
    elo_rating = request.form.get('elo_rating')

website/templates/about.html
{% extends "base.html" %}
{% block title %}About | Rank Realm{% endblock %}

{% block stylesheet %}
<link rel="stylesheet" href="../static/css/tutorial.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Petrona&display=swap">
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" id="tutorial-info">
    <h3 class="text-light" style="font-family: 'Petrona', sans-serif;">RankRealm is a lightweight ranking system built for indie developers that utilizes the
        established ELO algorithm
        for fairness and transparency. This provides a user-friendly website with an optional API for easy integration.
    </h3>
</div>
<div class="diagonal-separator"></div>
<div class="content-wrapper">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4" id="tutorial-card">
                <h2 style="font-family: 'Petrona', sans-serif;">Tutorial</h2>
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/VIDEO_ID"
                        allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-md-6 col-lg-4" id="example-card">
                <h2 style="font-family: 'Petrona', sans-serif;">Examples</h2>
                <img src="rocket-league-leaderboard.png" class="img-fluid" alt="Leaderboard Example">
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12 text-center">
                <h3 style="font-family: 'Petrona', sans-serif;">RankRealm</h3>
                <div class="line-break"></div>
                <p>Best ranking system for all gamers</p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

website/templates/add_event.html
{% extends "base.html" %}
{% block title %}Create Event | Rank Realm{% endblock %}

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Petrona&display=swap">
<style> 
body{
    font-family: 'Petrona', sans-serif;
}
h1 {
    font-weight: bold;
}
</style>
<div class="row">
    <div class="col-4 offset-4">
        <div class="card mt-5 mb-3">
            <form method="post">
                <h1 class="text-center my-5" id="welcome">Create Event</h1>
                <div class="card-body">
                    <label>Title:</label>
                    <input type="text" class="form-control" id="title" name="title" required>
                </div>
                <div class="card-body">
                    <label>Game:</label>
                    <select class="form-control" id="game_id" name="game_id" required>
                        {% for game in games %}
                        <option value="{{ game.id }}">{{ game.title }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="card-body">
                    <label>Host:</label>
                    <select class="form-control" id="host_id" name="host_id" required>
                        {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="card-body">
                    <label>Player:</label>
                    <select class="form-control" id="player_id" name="player_id" required>
                        {% for user in users %}
                        <option value="{{ user.id }}">{{ user.username }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="card-body">
                    <label>Start Date:</label>
                    <input type="datetime-local" class="form-control" id="start_date" name="start_date" required>
                </div>
                <div class="card-body">
                    <label>End Date:</label>
                    <input type="datetime-local" class="form-control" id="end_date" name="end_date" required>
                </div>
                <div class="text-center my-3">
                    <button type="submit" style="background-color: black; font-family: 'Petrona', sans-serif;" class="btn btn-primary">Create Event</button>

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

website/templates/admin_dashboard.html
{% extends "base.html" %}

{% block title %}Admin Panel{% endblock %}

{% block content %}
<div class="d-flex justify-content-between align-items-end mb-2">
  <h2 class="mt-4">Admin Dashboard</h2>
  <form action="{{ url_for('auth.admin_logout') }}" method="post" class="d-inline">
    <input type="hidden" name="logout" value="true">
    <button type="submit" class="btn btn-dark">Logout</button>
  </form>
</div>

<!-- Main navigation for this page -->
<div class="nav nav-tabs mb-3" id="nav-tab" role="tablist">
  <a class="nav-item nav-link active" id="nav-user-tab" data-bs-toggle="tab" href="#nav-user" role="tab" aria-controls="nav-user" aria-selected="true">Users</a>
  <a class="nav-item nav-link" id="nav-game-tab" data-bs-toggle="tab" href="#nav-game" role="tab" aria-controls="nav-game" aria-selected="false">Games</a>
  <a class="nav-item nav-link" id="nav-leaderboard-tab" data-bs-toggle="tab" href="#nav-leaderboard" role="tab" aria-controls="nav-leaderboard" aria-selected="false">Leaderboards</a>
  <a class="nav-item nav-link" id="nav-player-score-tab" data-bs-toggle="tab" href="#nav-player-score" role="tab" aria-controls="nav-player-score" aria-selected="false">Player Scores</a>
  <a class="nav-item nav-link" id="nav-event-tab" data-bs-toggle="tab" href="#nav-event" role="tab" aria-controls="nav-event" aria-selected="false">Events</a>
</div>

<div class="tab-content" id="nav-tabContent">
  <!-- User Management -->
  <div class="tab-pane px-3 show active" id="nav-user" role="tabpanel" aria-labelledby="nav-user-tab">
    <h3 class="mt-4">Users</h3>
    <form method="POST" action="{{ url_for('auth.add_user') }}">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" name="username" required>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
      </div>
      <div class="form-check">
        <input type="checkbox" class="form-check-input" id="is_game_owner" name="is_game_owner">
        <label class="form-check-label" for="is_game_owner">Is Game Owner</label>
      </div>
      <button type="submit" class="btn btn-dark mt-3">Add User</button>
    </form>

    <table class="table mt-5">
      <thead>
        <tr>
          <th>ID</th>
          <th>Username</th>
          <th>Email</th>
          <th>Is Game Owner</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.username }}</td>
          <td>{{ user.email }}</td>
          <td>{{ 'Yes' if user.is_game_owner else 'No' }}</td>
          <td>
            <a href="{{ url_for('auth.edit_user', user_id=user.id) }}" class="btn btn-dark btn-sm">Edit</a>
            <a href="{{ url_for('auth.delete_user', user_id=user.id) }}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this user? All associated data, including owned games, leaderboard entries, and player scores, will be deleted.')">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Game Management -->
  <div class="tab-pane px-3" id="nav-game" role="tabpanel" aria-labelledby="nav-game-tab">
    <h3 class="mt-4">Games</h3>
    <form method="POST" action="{{ url_for('auth.add_game') }}">
      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" required>
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
      </div>
      <div class="form-group">
        <label for="release_date">Release Date</label>
        <input type="date" class="form-control" id="release_date" name="release_date" required>
      </div>
      <div class="form-group">
        <label for="owner_id">Owner</label>
        <select class="form-control" id="owner_id" name="owner_id" required>
          {% for user in users %}
          {% if user.is_game_owner %}
          <option value="{{ user.id }}">{{ user.username }}</option>
          {% endif %}
          {% endfor %}
        </select>
      </div>
      <button type="submit" class="btn btn-dark">Add Game</button>
    </form>

    <table class="table mt-5">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Release Date</th>
          <th>Owner</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for game in games %}
        <tr>
          <td>{{ game.id }}</td>
          <td>{{ game.title }}</td>
          <td>{{ game.release_date }}</td>
          <td>{{ game.owner.username }}</td>
          <td>
            <a href="{{ url_for('auth.edit_game', game_id=game.id) }}" class="btn btn-dark btn-sm">Edit</a>
            <a href="{{ url_for('auth.delete_game', game_id=game.id) }}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this game? All associated leaderboards, player scores, and events will be deleted.')">Delete</a>
            <a href="{{ url_for('auth.transfer_ownership', game_id=game.id) }}" class="btn btn-warning btn-sm">Transfer Ownership</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Leaderboard Management -->
  <div class="tab-pane px-3" id="nav-leaderboard" role="tabpanel" aria-labelledby="nav-leaderboard-tab">
    <h3 class="mt-4">Leaderboards</h3>
    <form method="POST" action="{{ url_for('auth.add_leaderboard') }}">
      <div class="form-group">
        <label for="game_id">Game</label>
        <select class="form-control" id="game_id" name="game_id" required>
          {% for game in games %}
          <option value="{{ game.id }}">{{ game.title }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" id="name" name="name" required>
      </div>
      <button type="submit" class="btn btn-dark">Add Leaderboard</button>
    </form>

    <table class="table mt-5">
      <thead>
        <tr>
          <th>ID</th>
          <th>Game</th>
          <th>Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for leaderboard in leaderboards %}
        <tr>
          <td>{{ leaderboard.id }}</td>
          <td>{{ leaderboard.game.title }}</td>
          <td>{{ leaderboard.name }}</td>
          <td>
            <a href="{{ url_for('auth.edit_leaderboard', leaderboard_id=leaderboard.id) }}" class="btn btn-dark btn-sm">Edit</a>
            <a href="{{ url_for('auth.delete_leaderboard', leaderboard_id=leaderboard.id) }}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this leaderboard? All associated player scores will be deleted.')">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Player Score Management -->
  <div class="tab-pane px-3" id="nav-player-score" role="tabpanel" aria-labelledby="nav-player-score-tab">
    <h3 class="mt-4">Player Scores</h3>
    <form method="POST" action="{{ url_for('auth.add_player_score') }}">
      <div class="form-group">
        <label for="player_id">Player</label>
        <select class="form-control" id="player_id" name="player_id" required>
          {% for user in users %}
          <option value="{{ user.id }}">{{ user.username }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="leaderboard_id">Leaderboard:</label>
        <select class="form-control" id="leaderboard_id" name="leaderboard_id" required>
          {% for leaderboard in leaderboards %}
          <option value="{{ leaderboard.id }}">{{ leaderboard.game.title }} - {{ leaderboard.name }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="elo_rating">ELO Rating</label>
        <input type="number" class="form-control" id="elo_rating" name="elo_rating" required>
      </div>
      <div class="form-group">
        <label for="matches_played">Matches Played</label>
        <input type="number" class="form-control" id="matches_played" name="matches_played" required>
      </div>
      <div class="form-group">
        <label for="matches_won">Matches Won</label>
        <input type="number" class="form-control" id="matches_won" name="matches_won" required>
      </div>
      <div class="form-group">
        <label for="matches_lost">Matches Lost</label>
        <input type="number" class="form-control" id="matches_lost" name="matches_lost" required>
      </div>
      <button type="submit" class="btn btn-dark">Add Player Score</button>
    </form>

    <table class="table mt-5">
      <thead>
        <tr>
          <th>ID</th>
          <th>Player</th>
          <th>Leaderboard</th>
          <th>ELO Rating</th>
          <th>Matches Played</th>
          <th>Matches Won</th>
          <th>Matches Lost</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for player_score in player_scores %}
        <tr>
          <td>{{ player_score.id }}</td>
          <td>{{ player_score.player.username }}</td>
          <td>{{ player_score.leaderboard.game.title }} - {{ player_score.leaderboard.name }}</td>
          <td>{{ player_score.elo_rating }}</td>
          <td>{{ player_score.matches_played }}</td>
          <td>{{ player_score.matches_won }}</td>
          <td>{{ player_score.matches_lost }}</td>
          <td>
            <a href="{{ url_for('auth.edit_player_score', player_score_id=player_score.id) }}" class="btn btn-dark btn-sm">Edit</a>
            <a href="{{ url_for('auth.delete_player_score', player_score_id=player_score.id) }}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this player score?')">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

<!-- Event Management -->
<div class="tab-pane px-3" id="nav-event" role="tabpanel" aria-labelledby="nav-event-tab">
  <h3 class="mt-4">Events</h3>
  <form method="POST" action="{{ url_for('auth.add_event') }}">
    <div class="form-group">
      <label for="game_id">Game</label>
      <select class="form-control" id="game_id" name="game_id" required>
        {% for game in games %}
        <option value="{{ game.id }}">{{ game.title }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="owner_id">Owner</label>
      <select class="form-control" id="owner_id" name="owner_id" required>
        {% for user in users %}
        <option value="{{ user.id }}">{{ user.username }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="start_date">Start Date</label>
      <input type="datetime-local" class="form-control" id="start_date" name="start_date" required>
    </div>
    <div class="form-group">
      <label for="end_date">End Date</label>
      <input type="datetime-local" class="form-control" id="end_date" name="end_date" required>
    </div>
    <button type="submit" class="btn btn-dark">Add Event</button>
  </form>

  <table class="table mt-5">
    <thead>
      <tr>
        <th>ID</th>
        <th>Game</th>
        <th>Owner</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for event in events %}
      <tr>
        <td>{{ event.id }}</td>
        <td>{{ event.game.title }}</td>
        <td>{{ event.owner.username }}</td>
        <td>{{ event.start_date }}</td>
        <td>{{ event.end_date }}</td>
        <td>
          <a href="{{ url_for('auth.edit_event', event_id=event.id) }}" class="btn btn-dark btn-sm">Edit</a>
          <a href="{{ url_for('auth.delete_event', event_id=event.id) }}" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this event?')">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

website/templates/admin_login.html
{% extends "base.html" %} {% block title %}Admin Login{% endblock %} {% block content %}
<h2 class="mt-4">Admin Login</h2>

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }}">{{ message }}</div>
{% endfor %}
{% endif %}
{% endwith %}

<form class="pl-0 col-lg-9" method="POST">
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" name="password" required>
  </div>
  <button type="submit" class="btn btn-dark">Login</button>
</form>
{% endblock %}

website/templates/edit_game.html
{% extends "base.html" %}
{% block title %}Edit Game | Rank Realm{% endblock %}

{% block content %}
<div class="row">
    <div class="col-4 offset-4">
        <div class="card mt-5 mb-3">
            <form method="post">
                <h1 class="text-center my-5" id="welcome">Edit Game</h1>
                <div class="card-body">
                    <label>Title:</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ game.title }}" required>
                </div>
                <div class="card-body">
                    <label>Description:</label>
                    <textarea class="form-control" id="description" name="description" rows="3" required>{{ game.description }}</textarea>
                </div>
                <div class="card-body">
                    <label>Release Date:</label>
                    <input type="date" class="form-control" id="release_date" name="release_date" value="{{ game.release_date.strftime('%Y-%m-%d') }}" required>
                </div>
                <div class="card-body">
                    <label>Owner:</label>
                    <select class="form-control" id="owner_id" name="owner_id" required>
                        {% for user in users %}
                        <option value="{{ user.id }}" {% if user.id == game.owner_id %}selected{% endif %}>{{ user.username }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-center my-3">
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login | Rank Realm{% endblock %}

{% block content %}
<link rel="stylesheet" href="../static/css/login.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Petrona&display=swap">
<div class="row">
    <div class="col-4 offset-4">
        <div class="card mt-5 mb-3">
            <form method="post">
                <h1 class="text-center my-5" id="welcome">Sign in</h1>
                <div class="card-body">
                     <input type="text" class="form-control" id="email" name="email" placeholder="Email" name="email">
                </div>
                <div class="card-body">
                <input type="password" class="form-control" id="password1" name="password1" placeholder="Password" name="pwd1">
                </div>
                <div class="text-center my-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
                <p class="text-center my-3">Don't have an account?  <a class="bottom" href="{{url_for('auth.sign_up')}}"> Register here</a></p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/transfer_ownership.html
{% extends "base.html" %}

{% block title %}Transfer Game Ownership | Admin Panel{% endblock %}

{% block content %}
<h1>Transfer Game Ownership</h1>

<h2>Game: {{ game.title }}</h2>

<form method="POST" action="{{ url_for('auth.transfer_ownership', game_id=game.id) }}">
  <div class="form-group">
    <label for="new_owner_id">New Owner:</label>
    <select class="form-control" id="new_owner_id" name="new_owner_id" required>
      {% for owner in game_owners %}
      <option value="{{ owner.id }}">{{ owner.username }}</option>
      {% endfor %}
    </select>
  </div>
  <button type="submit" class="btn btn-warning">Transfer Ownership</button>
</form>

{% endblock %}